### PR TITLE
Code review comments

### PR DESCRIPTION
**Pull request by chieakiba**
Hi Jay,

I reviewed your code and made some comments. 
Let me know if you have any questions.
Hope this helps :)

Thanks,
Chie

### CODE REVIEW

**Comment by jayzamazing** [comment]
The not loading in your browser thing sounds like a local problem. I have tested this in firefox, chrome, and safari without any issues using the gh-pages version which is hosted at  https://jayzamazing.github.io/Pirate-Bartender-Project . I would try clearing your cache and trying again or updating your browser. If the issue persists, please provide additional information such as system you are running this on, browser, and version of browser.

**Comment by jayzamazing** [comment]
I will look into the other issues, but for these issues I will work on them rather than merging this pull request.

**Comment by jayzamazing** [comment]
Closed by mistake without addressing issues.

**Comment by jayzamazing** [comment]
Added comments to style.css, made comments inline in app.js. If the browser is still not reloading the app.js file open a bug rather than a pull request and provide more details. Closing this pull request without merging.

**Comment by chieakiba** [comment]
ohh yea, I can see the website now.

**Comment by miclovich** [comment]
👍

**Pull request closed without merging**
